# Site
name: "Peter Mikitsh"
title: "A tech blog by Peter Mikitsh"
description: "Personal blog for tech things."
logo: 'assets/images/1x1.png'
favicon: 'assets/images/1x1.png'
baseurl: ''
include: ["_pages"]
permalink: post/:title/

# Authors
authors:
  pete:
    name: pete
    display_name: Peter Mikitsh
    gravatar: b829ad87beb8ed2fba8a5300c5ee6292
    email: peter.mikitsh@gmail.com
    web: https://mikit.sh
    twitter: https://twitter.com/petermikitsh
    description: "Software Engineer @ Zuora, former SWE @ Intuit. Southern California. RIT Alum. he/him"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
